version: "3.8"

services:
  backend:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

  frontend:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

  db:
    build: ./services/db
    command: python manage.py migrate
    volumes:
      - ./services/db/:/usr/src/app/
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev
